/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockINR__factory } from "./MockINR__factory";
export { MockInsurance__factory } from "./MockInsurance__factory";
